const GAMES = {
	NUMBER_GUESSER: 'NUMBER_GUESSER',
	ROCK_PAPER_SCISSOR: 'ROCK_PAPER_SCISSOR',
} as const;

const GAME_URL_MAP = {
	'/number-guesser': GAMES.NUMBER_GUESSER,
	'/rock-paper-scissor': GAMES.ROCK_PAPER_SCISSOR,
};

const ROOM_OPERATION = {
	INFO: 'INFO',
	MODAL_INFO: 'MODAL_INFO',
	CHAT: 'CHAT',
	GAME: 'GAME',
	PLAYER_TURN: 'PLAYER_TURN',
	END_PLAYER_TURN: 'END_PLAYER_TURN',
	OPPONENT: 'OPPONENT',
	TIMER: 'TIMER',
	RESET: 'RESET',
	REPLAY: 'REPLAY',
	RESULT: 'RESULT',
	OPPONENT_LEFT: 'OPPONENT_LEFT',
} as const;


const GAME_CONFIGURATION = {
	FIRST_PLAYER: 0,
	TARGET_LIMIT: 100
}

export default {
	GAMES,
	ROOM_OPERATION,
	GAME_CONFIGURATION,
	GAME_URL_MAP,
};
